# Matrices
Matrices are vectors with dimension attribute.  Dimension attribute is an integer vector of length 2 (nrow, ncol)

In [1]:
m <- matrix(nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA


#### Check dimension of the matrix with dim() function

In [2]:
dim(m)

[1] 2 3

In [3]:
attributes(m)

$dim
[1] 2 3

## Matrices are constructed column-wise, from upper left going down the column

In [4]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


#### Matrices can be created from a vector by adding a dimension attribute
Dimension is itself a vector

In [5]:
m <- 1:10
print(m)

 [1]  1  2  3  4  5  6  7  8  9 10


In [6]:
dim(m) <- c(2,5)
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


## Matrices can be created by column-binding with cbind() or row-binding with rbind()

In [7]:
x <- 1:3
y <- 10:12
m1 <- cbind(x,y)
print(m1)

     x  y
[1,] 1 10
[2,] 2 11
[3,] 3 12


In [8]:
m2 <- rbind(x,y)
print(m2)

  [,1] [,2] [,3]
x    1    2    3
y   10   11   12
