# Matrices
Matrices are vectors with dimension attribute.  Dimension attribute is an integer vector of length 2 (nrow, ncol)

In [1]:
m <- matrix(nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA


#### Check dimension of the matrix with dim() function

In [2]:
dim(m)

[1] 2 3

In [3]:
attributes(m)

$dim
[1] 2 3

## Matrices are constructed column-wise, from upper left going down the column

In [4]:
m <- matrix(1:6, nrow=2, ncol=3)
print(m)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


#### Matrices can be constructed row-wise using byrow=TRUE parameter 

In [5]:
m <- matrix(1:6, nrow=2, ncol=3, byrow=TRUE)
print(m)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


#### Matrices can be created from a vector by adding a dimension attribute
Dimension is itself a vector

In [6]:
m <- 1:10
print(m)

 [1]  1  2  3  4  5  6  7  8  9 10


In [7]:
dim(m) <- c(2,5)
print(m)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


## Matrices can be created by column-binding with cbind() or row-binding with rbind()

In [8]:
x <- 1:3
y <- 10:12
m1 <- cbind(x,y)
print(m1)

     x  y
[1,] 1 10
[2,] 2 11
[3,] 3 12


In [9]:
m2 <- rbind(x,y)
print(m2)

  [,1] [,2] [,3]
x    1    2    3
y   10   11   12


## Vectorized Matrix Operations

In [10]:
x <- matrix(1:4, 2, 2)
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [11]:
y <- matrix(rep(10, 4), 2, 2)
y

[,1] [,2]
[1,] 10   10  
[2,] 10   10

#### Element-wise mulpiplication

In [12]:
x * y

[,1] [,2]
[1,] 10   30  
[2,] 20   40

#### True Matrix multiplication

In [13]:
x %*% y

[,1] [,2]
[1,] 40   40  
[2,] 60   60