# Apply Functions:
- lapply: Loop over a list and evaluate a function on each element (returns a list)
- sapply: Same as lapply but try to simplify the result (returns a vector if possible)
- apply: Apply a function over the margins of an array
- tapply: Apply a function over subsets of a vector
- mapply: Multivariate version of lapply

## lapply:
- 3 arguments: list, function to be applied, arguments for the function
- If not list, will be coerced into a list
- Always returns a list

#### Example 1:

In [1]:
x <- list(a=1:5, b=rnorm(10))
x

$a
[1] 1 2 3 4 5

$b
 [1] -0.95026003 -1.14036650  0.32145905 -0.05627709  0.11344642 -0.23468176
 [7]  0.17684138 -0.75237473 -2.80717458 -1.24580479

#### Compute mean of each element of the list

In [2]:
lapply(x, mean)

$a
[1] 3

$b
[1] -0.6575193

#### Example 2: With function parameters

In [3]:
x <- 1:4
new_list <- lapply(x, runif)
new_list

[[1]]
[1] 0.2759969

[[2]]
[1] 0.3483987 0.3498624

[[3]]
[1] 0.9354807 0.1972798 0.2055821

[[4]]
[1] 0.4059983 0.2303605 0.2233870 0.4403360

In [4]:
class(new_list)

[1] "list"

In [5]:
x <- 1:4
new_list <- lapply(x, runif, min=0, max=10)
new_list

[[1]]
[1] 7.428947

[[2]]
[1] 4.279287 6.163883

[[3]]
[1] 8.241506 4.207476 7.960665

[[4]]
[1] 1.464036 3.680062 3.132659 8.399110

#### Example 3: Using anonymous functions to subset a matrix

In [6]:
x <- list(a=matrix(1:4,2,2), b=matrix(1:6,3,2))
x

$a
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$b
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

In [7]:
#Extract 1st column
lapply(x, function(m) m[,1])

$a
[1] 1 2

$b
[1] 1 2 3

## sapply
- Will try to simplify results of lapply
- will coerce into a vector if the result is a list where each element is of length 1
- Returns matrix if every element is a vector of the same length greater than 1
- Returns list otherwise

#### Example 1: Returning a vector

In [8]:
x <- list(a=1:4, b=rnorm(10), c=rnorm(20,1), d=rnorm(100,5))

In [9]:
result <- lapply(x, mean)
result

$a
[1] 2.5

$b
[1] 0.07995016

$c
[1] 1.05199

$d
[1] 4.960048

In [10]:
result <- sapply(x, mean)
result

a          b          c          d 
2.50000000 0.07995016 1.05198994 4.96004809

In [11]:
class(result)

[1] "numeric"

#### Example 2: Returning a matrix
- column wise

In [12]:
x <- list(rnorm(4), runif(4,min=5, max=6))
x

[[1]]
[1] -0.4756721 -0.5187210 -0.2500033  0.7180881

[[2]]
[1] 5.599207 5.668563 5.907267 5.834385

In [13]:
result <- sapply(x, function(elem) elem)
print(result)

           [,1]     [,2]
[1,] -0.4756721 5.599207
[2,] -0.5187210 5.668563
[3,] -0.2500033 5.907267
[4,]  0.7180881 5.834385


## apply
- Can be used to apply a function to the rows and columns of the matrix
- margin: 1 is for columns (across rows), 2 for rows (across columns)

In [14]:
str(apply)

function (X, MARGIN, FUN, ...)  


In [15]:
x <- matrix(rnorm(200), 5, 10)
x

[,1]       [,2]       [,3]       [,4]       [,5]        [,6]       
[1,]  0.5162986 -0.2826330 -1.6445688  0.3130639 -0.72670443 -0.63948173
[2,] -0.1271013  2.0511788 -0.1713035  0.8280269  0.43234682  0.02922295
[3,]  0.4625589 -0.9307099 -0.7934769 -1.0540611  0.03609792 -0.44226092
[4,]  1.5394236  1.8195162 -1.4970269 -0.6411848  0.98814995  0.52303809
[5,] -0.6268383  0.8368587 -0.9105251 -0.3001891 -1.38040746 -0.40743874
     [,7]        [,8]       [,9]       [,10]     
[1,] -0.69175643 -1.3728104 -1.0816178  0.4064905
[2,] -0.34451577  0.2273051 -0.6727672 -0.1523613
[3,] -1.04704715  1.5124678 -0.5914131  1.3226529
[4,]  0.88377157 -0.1959525 -1.3353139 -2.2419094
[5,]  0.03236875  1.8716447  1.3140836 -0.3726316

#### Sum of the columns (adding all rows)
- Can also use built-in rowSums() and rowMeans() functions

In [16]:
apply(x, 1, sum)

[1] -5.2037196  2.1000315 -1.5251915 -0.1574880  0.0569253

In [17]:
rowSums(x)

[1] -5.2037196  2.1000315 -1.5251915 -0.1574880  0.0569253

#### Sum of the rows (adding all columns)
- Can also use built-in colSums() and colMeans() functions

In [18]:
apply(x, 2, sum)

[1]  1.7643414  3.4942108 -5.0169011 -0.8543443 -0.6505172 -0.9369203
 [7] -1.1671790  2.0426547 -2.3670284 -1.0377589

In [19]:
colSums(x)

[1]  1.7643414  3.4942108 -5.0169011 -0.8543443 -0.6505172 -0.9369203
 [7] -1.1671790  2.0426547 -2.3670284 -1.0377589